### ISSUE TITLE
Smarter Signatures: Crypto-conditions disadvantages not correct

### ISSUE THREAD

**Issue by adrianhopebailie** [WebOfTrustInfo/ID2020DesignWorkshop#21]
The following statement is not correct:

> It is also somewhat limited, since its core concept of holding funds has limited scope (but is a solid starting point).

Crypto-conditions are not limited to holding funds. That is how they are used in the [Interledger Protocol](https://interledger.org) but that is not a limitation of the technology itself.

**Comment by shannona** [comment]
Thank much, I've cut that sentence per your suggestion. However, if you have any other ideas for what people should be talking about for possible limitations or disadvantages of the approach, as I'd love to hear them, as the objective is to create a dialogue about all these possibilities.

**Comment by adrianhopebailie** [comment]
@shannona I think the biggest issue with crypto-conditions is their relative immaturity which in crypto is a disadvantage.

**Comment by adrianhopebailie** [comment]
@shannona I think the biggest issue with crypto-conditions is their relative immaturity which in crypto is a disadvantage.
