### ISSUE TITLE
Noticing that all documents in /topics-and-advance-readings are not linked in the readme.

### ISSUE THREAD

**Issue by infominer33** [WebOfTrustInfo/ID2020DesignWorkshop#28]
I will be happy to add links to the readme for any topics and advance readings not already linked (and will end up doing so for my own research collection, anyways).

However, it would be helpful to know if there is a specific reasoning that some were not included (and perhaps should have their own section in the readme), or maybe they were simply added after the readme was made.

As I'm working to index this information and make it more accessible, I'm noticing the same thing with other rwot repositories.

-Please Advise.

**Comment by ChristopherA** [comment]
Everything in topics should be ultimately indexed with abstract in the topics README.md, as the root README.md will be repurposed now that drafts are arriving. 

We are open to other organizational thoughts, but anything we do needs to respect @shannona’s time as he will have 25 papers to edit (one a week between now and #rwot9!)
